### ISSUE TITLE
Error: data and salt arguments required

### ISSUE THREAD

**Issue by pankaja92** [generalgmt/RESTfulAPITutorial#6]
After cloned the project I've updated according to new mongoose version by adding `**'useMongoClient : true'** `. And the project is running ok.

When I send 'localhost:3000/auth/register' POST request via postman I'm getting this error. Is it a bug ? Or what have I done wrong ?

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Error: data and salt arguments required
            <br> &nbsp; &nbsp;at Object.hashSync (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/bcrypt/bcrypt.js:71:15)
            <br> &nbsp; &nbsp;at exports.register (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/api/controllers/userController.js:9:34)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at next (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/route.js:137:13)
            <br> &nbsp; &nbsp;at Route.dispatch (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/route.js:112:3)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at /home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/index.js:281:22
            <br> &nbsp; &nbsp;at Function.process_params (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/index.js:335:12)
            <br> &nbsp; &nbsp;at next (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at jsonParser (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/body-parser/lib/types/json.js:112:7)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/index.js:317:13)
            <br> &nbsp; &nbsp;at /home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/index.js:335:12)
            <br> &nbsp; &nbsp;at next (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at urlencodedParser (/home/pankaja/Projects/Nodejs/Tutorial/todoApp/RESTfulAPITutorial/node_modules/body-parser/lib/types/urlencoded.js:100:7)
        </pre>
    </body>
</html>
```

**Comment by generalgmt** [comment]
Which of the branches are you talking about?

**Comment by gromit6891** [comment]
I'm getting the same error on registration. This is the 'Authentication' branch.

**Comment by generalgmt** [comment]
From the look of things, you are not sending the password field to the backend.
Could you show me the way you are posting to the backend? @pankaja92

**Comment by jeetukateja** [comment]
The problem is the value of user i.e. user.password is not getting passed from usercontroller to usermodel compare password method. I have checked by console.log(); Please find attached scrrenshot for referece.

![image](https://user-images.githubusercontent.com/36131023/35778360-0d20315c-09e3-11e8-9c5a-24a02ebba4e3.png)

**Comment by generalgmt** [comment]
@jeetukateja  Here is the thing, the value of user you consoled out there is the user that is returned from the database whenever a user with that email address is found in the database.
What you need to do is to log out the object you are posting to the backend immediately inside the sign in function.
<img width="858" alt="screen shot 2018-02-04 at 3 44 14 pm" src="https://user-images.githubusercontent.com/7859083/35778727-7ee9f1e0-09c2-11e8-8315-3a12b41b1ed6.png">

**Comment by jayliew** [comment]
I had the same problem, turns out the issue was that when I was sending the POST request from Insomnia, I had it send as *Multipart Form* as opposed to using *Form URL Encoded*.

**Comment by ogagaCodes** [comment]
I solved this too by removing the enctype attribute of the form entirely.
Just do 
`<form action ="..." method="post">.....</form>`

and not 
`<form action ="..." method="post" enctype = "....">........</form>`
