### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by yphil-dev** [generalgmt/RESTfulAPITutorial#9]
```
# git clone https://github.com/generalgmt/RESTfulAPITutorial.git && cd RESTfulAPITutorial

# npm install

# npm run start

> todolistapi@1.0.0 start /home/px/src/RESTfulAPITutorial
> nodemon server.js

[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
todo list RESTful API server started on: 3000
```

In the JS console:

`Content Security Policy: Couldn't process unknown directive 'report-to'`

http://localhost:3000/tasks doesn't respond ; the loading icon keeps spinning ; Oh well, 10 (more like 25) minutes down the drain :)

PS - just to be sure, I tried running it with pm2 ; no luck :(

**Comment by DaoFof** [comment]
try this [https://github.com/DaoFof/node-course-2-todo-api.git](url)
